name: Leosin
display_name: Leosin
version: 3.0.0
author:
  name: "Jan Heder"
  email: "info@janheder.cz"
  url: "https://janheder.cz"

meta:
  compatibility:
      from: 1.7.2.0
      to: ~

  available_layouts:
    layout-full-width:
      name: Full Width
      description: No side columns, ideal for distraction-free pages such as product pages.
    layout-both-columns:
      name: Three Columns
      description: One large central column and 2 side columns.
    layout-left-side-column:
      name: Two Columns, small left column
      description: Two columns with a small left column
    layout-right-side-column:
      name: Two Columns, small right column
      description: Two columns with a small right column

global_settings:
  configuration:
    PS_QUICK_VIEW: false

  hooks:
    custom_hooks:
      - name: displayFooterBefore
        title: displayFooterBefore
        description: Add a widget area above the footer
    modules_to_hook:
      displayNav:
        - ps_searchbar
        - ps_languageselector
        - ps_currencyselector
        - ps_customersignin
        - ps_shoppingcart
      displayTop:
        - ps_mainmenu
      displayHome:
        - ps_imageslider
        - ps_featuredproducts
        - ps_banner
      displayFooter:
        - ps_linklist
        - ps_customeraccountlinks
        - ps_contactinfo


  image_types:
    cart_default:
      width: 80
      height: 80
      scope: [products]
    small_default:
      width: 125
      height: 125
      scope: [products, categories, manufacturers, suppliers]
    medium_default:
      width: 300
      height: 300
      scope: [products, categories, manufacturers, suppliers]
    large_default:
      width: 500
      height: 500
      scope: [products]
    home_default:
      width: 250
      height: 250
      scope: [products]
    category_default:
      width: 960
      height: 350
      scope: [categories]
    stores_default:
      width: 170
      height: 115
      scope: [stores]

theme_settings:
  default_layout: layout-full-width

  layouts:
    category: layout-left-side-column
    best-sales: layout-left-side-column

assets:
  js:
    all:
      - id: js-popper
        path: assets/js/popper.min.js
        media: all
        priority: 200

      - id: js-bootstrap
        path: assets/js/bootstrap.min.js
        media: all
        priority: 300

      - id: js-swiper
        path: assets/js/swiper.min.js
        media: all
        priority: 400

      - id: js-lazyload
        path: assets/js/lazyload.min.js
        media: all
        priority: 500

      - id: js-scripts
        path: assets/js/scripts.min.js
        media: all
        priority: 600


